// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3Dkvcai88ZDDXz01k82JuXg7VXAS3tk',
    appId: '1:225418999366:android:906e81146959512cf8fc47',
    messagingSenderId: '225418999366',
    projectId: 'fypar-819e4',
    storageBucket: 'fypar-819e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gxlviBkr485ACzTIkqkj2bqbGLr2SCk',
    appId: '1:225418999366:ios:d60e9e90032cda75f8fc47',
    messagingSenderId: '225418999366',
    projectId: 'fypar-819e4',
    storageBucket: 'fypar-819e4.appspot.com',
    androidClientId: '225418999366-jfs8273i5og01otvh8ilccev8n3gvagf.apps.googleusercontent.com',
    iosClientId: '225418999366-eqlmp6uhj0827vrklj7gakdpc0uflpoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseConceptsApp',
  );
}
